import { createNodePlugin } from '../../domain/plugins';

export const codePlugin = createNodePlugin({
  id: 'code',
  priority: 10,
  defaultInfo: {
    iconClass: 'fas fa-file-code',
    className: 'code',
  },
  extensions: {
    json: { mime: 'application/json' },
    xml: { mime: 'application/xml' },
    html: { mime: 'text/html' },
    htm: { mime: 'text/html' },
    css: { mime: 'text/css' },
    js: { mime: 'text/javascript' },
    mjs: { mime: 'text/javascript' },
    cjs: { mime: 'text/javascript' },
    ts: { mime: 'text/typescript' },
    tsx: { mime: 'text/typescript-jsx' },
    jsx: { mime: 'text/javascript-jsx' },
    yaml: { mime: 'text/yaml' },
    yml: { mime: 'text/yaml' },
    toml: { mime: 'text/toml' },
    ini: { mime: 'text/plain' },
    cfg: { mime: 'text/plain' },
    conf: { mime: 'text/plain' },
    list: { mime: 'text/plain' },
    reg: { mime: 'text/plain' },
    ps1: { iconClass: 'fas fa-terminal', mime: 'text/plain' },
    sh: { iconClass: 'fas fa-terminal', mime: 'text/plain' },
    bash: { iconClass: 'fas fa-terminal', mime: 'text/plain' },
    zsh: { iconClass: 'fas fa-terminal', mime: 'text/plain' },
    bat: { iconClass: 'fas fa-terminal', mime: 'text/plain' },
    py: { mime: 'text/x-python' },
    rb: { mime: 'text/x-ruby' },
    php: { mime: 'text/x-php' },
    java: { mime: 'text/x-java' },
    c: { mime: 'text/x-c' },
    cpp: { mime: 'text/x-c++' },
    h: { mime: 'text/x-c' },
    hpp: { mime: 'text/x-c++' },
    rs: { mime: 'text/x-rust' },
    go: { mime: 'text/x-go' },
    swift: { mime: 'text/x-swift' },
    kt: { mime: 'text/x-kotlin' },
    scala: { mime: 'text/x-scala' },
    lua: { mime: 'text/x-lua' },
    r: { mime: 'text/x-r' },
    sql: { iconClass: 'fas fa-database', mime: 'text/x-sql' },
    graphql: { mime: 'application/graphql' },
    vue: { mime: 'text/x-vue' },
    svelte: { mime: 'text/x-svelte' },
  },
  preview: async () =>
    (await import('../../features/preview/renderers/CodePreview.vue')).default,
});
