name: 检查代码

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'README.md'
  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: check-code-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-code:
    runs-on: ubuntu-latest

    steps:
      - name: 签出仓库
        uses: actions/checkout@v6

      - name: 安装 pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11.2.2

      - name: 安装 Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '26.2.0'
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: 安装依赖
        run: pnpm install --frozen-lockfile

      - name: 检查代码
        run: pnpm run verify
