name: 通过 GitHub Pages 部署网站
on:
  push:
    branches:
      - 'file'
    paths-ignore:
      - 'README.md'
  pull_request:
    branches:
      - 'file'
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: 签出仓库
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: 安装 pnpm
        uses: pnpm/action-setup@v6

      - name: 安装 NodeJS
        uses: actions/setup-node@v6
        with:
          cache: 'pnpm'

      - name: 安装依赖
        run: pnpm install --frozen-lockfile

      - name: 运行生成脚本
        run: pnpm run build

      - name: 列出构建产物（调试）
        run: |
          echo "构建输出"
          ls -la ./ || true

      - name: 删除应忽略的文件
        run: |
          echo "删除不需要部署的文件..."
          rm -rf node_modules

      - name: 检查更改
        id: git-check
        run: |
          echo "检查是否有文件被修改..."
          if git diff --quiet; then
            echo "没有检测到更改"
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "检测到文件更改"
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: 配置 Git 并提交更改
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "🐎 ci(share-file.json): 自动生成文件索引 [skip ci]"
          git push

      - name: 上传页面
        uses: actions/upload-pages-artifact@v5
        with:
          path: './'

      - name: 部署页面
        id: deployment
        uses: actions/deploy-pages@v5
